# Generated by Django 4.0 on 2023-06-30 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('send_timestamp', models.DateTimeField(auto_now_add=True)),
                ('view_timestamp', models.DateTimeField(blank=True, null=True)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='auth.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='auth.user')),
            ],
        ),
    ]
