# Generated by Django 4.0 on 2023-07-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='plagiarized_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Codes.code'),
        ),
    ]
