# Generated by Django 4.0 on 2023-06-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0002_tag_file_extension_alter_codetags_code_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeTags',
            new_name='CodeTag',
        ),
    ]
