# Generated by Django 4.0 on 2023-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0003_rename_codetags_codetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Codes.tag'),
        ),
        migrations.DeleteModel(
            name='CodeTag',
        ),
    ]
